const ListaPaises = [
  { value: 'Brasil', label: 'Brasil', regiao: 'BR' },
  { value: 'Múltiplos Destinos', label: 'Múltiplos Destinos', regiao: '8' },

  //Estados Unidos e Canadá
  { value: 'Estados Unidos', label: 'Estados Unidos', regiao: 'EUA' },
  { value: 'Canadá', label: 'Canadá', regiao: 'CAN' },

  // Europa
  { value: 'França', label: 'França', regiao: 'FRA', CodigoTipoProduto: 'VI' },
  {
    value: 'Espanha',
    label: 'Espanha',
    regiao: 'ESP',
    CodigoTipoProduto: 'VI',
  },
  { value: 'Itália', label: 'Itália', regiao: 'ITA', CodigoTipoProduto: 'VI' },
  {
    value: 'Reino Unido',
    label: 'Reino Unido',
    regiao: 'GBR',
    CodigoTipoProduto: 'VI',
  },
  {
    value: 'Alemanha',
    label: 'Alemanha',
    regiao: 'DEU',
    CodigoTipoProduto: 'VI',
  },
  { value: 'Grécia', label: 'Grécia', regiao: 'GRC', CodigoTipoProduto: 'VI' },
  { value: 'Portugal', label: 'Portugal', regiao: 'PRT' },
  { value: 'Áustria', label: 'Áustria', regiao: 'AUT' },
  { value: 'Turquia', label: 'Turquia', regiao: 'TUR' },
  { value: 'Bélgica', label: 'Bélgica', regiao: 'BEL' },
  { value: 'Holanda', label: 'Holanda', regiao: 'NLD' },
  { value: 'Suíça', label: 'Suíça', regiao: 'CHE' },
  { value: 'Suécia', label: 'Suécia', regiao: 'SWE' },
  { value: 'Noruega', label: 'Noruega', regiao: 'NOR' },
  { value: 'Dinamarca', label: 'Dinamarca', regiao: 'DNK' },
  { value: 'Albânia', label: 'Albânia', regiao: 'ALB' },
  { value: 'Andorra', label: 'Andorra', regiao: 'AND' },
  { value: 'Armênia', label: 'Armênia', regiao: 'ARM' },
  { value: 'Bielorrússia', label: 'Bielorrússia', regiao: 'BLR' },
  {
    value: 'Bósnia e Herzegovina',
    label: 'Bósnia e Herzegovina',
    regiao: 'BIH',
  },
  { value: 'Bulgária', label: 'Bulgária', regiao: 'BGR' },
  { value: 'Chipre', label: 'Chipre', regiao: 'CYP' },
  { value: 'Croácia', label: 'Croácia', regiao: 'HRV' },
  { value: 'Eslováquia', label: 'Eslováquia', regiao: 'SVK' },
  { value: 'Eslovênia', label: 'Eslovênia', regiao: 'SVN' },
  { value: 'Estônia', label: 'Estônia', regiao: 'EST' },
  { value: 'Finlândia', label: 'Finlândia', regiao: 'FIN' },
  { value: 'Geórgia', label: 'Geórgia', regiao: 'GEO' },
  { value: 'Hungria', label: 'Hungria', regiao: 'HUN' },
  { value: 'Irlanda', label: 'Irlanda', regiao: 'IRL' },
  { value: 'Islândia', label: 'Islândia', regiao: 'ISL' },
  { value: 'Letônia', label: 'Letônia', regiao: 'LVA' },
  { value: 'Liechtenstein', label: 'Liechtenstein', regiao: 'LIE' },
  { value: 'Lituânia', label: 'Lituânia', regiao: 'LTU' },
  { value: 'Luxemburgo', label: 'Luxemburgo', regiao: 'LUX' },
  { value: 'Macedônia do Norte', label: 'Macedônia do Norte', regiao: 'MKD' },
  { value: 'Malta', label: 'Malta', regiao: 'MLT' },
  { value: 'Moldávia', label: 'Moldávia', regiao: 'MDA' },
  { value: 'Mônaco', label: 'Mônaco', regiao: 'MCO' },
  { value: 'Montenegro', label: 'Montenegro', regiao: 'MNE' },
  { value: 'Polônia', label: 'Polônia', regiao: 'POL' },
  { value: 'República Tcheca', label: 'República Tcheca', regiao: 'CZE' },
  { value: 'Romênia', label: 'Romênia', regiao: 'ROU' },
  { value: 'Rússia', label: 'Rússia', regiao: 'RUS' },
  { value: 'San Marino', label: 'San Marino', regiao: 'SMR' },
  { value: 'Sérvia', label: 'Sérvia', regiao: 'SRB' },
  { value: 'Ucrânia', label: 'Ucrânia', regiao: 'UKR' },
  { value: 'Vaticano', label: 'Vaticano', regiao: 'VAT' },
  { value: 'Azerbaijão', label: 'Azerbaijão', regiao: 'AZE' },
  { value: 'Ilhas Faroé', label: 'Ilhas Faroé', regiao: 'FRO' },
  { value: 'Gibraltar', label: 'Gibraltar', regiao: 'GIB' },
  { value: 'Kosovo', label: 'Kosovo', regiao: 'XKX' },
  { value: 'Ilha de Man', label: 'Ilha de Man', regiao: 'IMN' },
  { value: 'Escócia', label: 'Escócia', regiao: 'SCO' },
  { value: 'País de Gales', label: 'País de Gales', regiao: 'WLS' },
  {
    value: 'Ilhas Svalbard e Jan Mayen',
    label: 'Ilhas Svalbard e Jan Mayen',
    regiao: 'SJM',
  },

  // América Latina (inclui México)
  { value: 'Argentina', label: 'Argentina', regiao: 'ARG' },
  { value: 'Bolívia', label: 'Bolívia', regiao: 'BOL' },
  { value: 'Chile', label: 'Chile', regiao: 'CHL' },
  { value: 'Colômbia', label: 'Colômbia', regiao: 'COL' },
  { value: 'Cuba', label: 'Cuba', regiao: 'CUB' },
  { value: 'Equador', label: 'Equador', regiao: 'ECU' },
  { value: 'Guiana', label: 'Guiana', regiao: 'GUY' },
  { value: 'Paraguai', label: 'Paraguai', regiao: 'PRY' },
  { value: 'México', label: 'México', regiao: 'MEX' },
  { value: 'Peru', label: 'Peru', regiao: 'PER' },
  { value: 'Suriname', label: 'Suriname', regiao: 'SUR' },
  { value: 'Uruguai', label: 'Uruguai', regiao: 'URY' },
  { value: 'Venezuela', label: 'Venezuela', regiao: 'VEN' },
  { value: 'El Salvador', label: 'El Salvador', regiao: 'SLV' },

  // Ásia
  { value: 'Afeganistão', label: 'Afeganistão', regiao: 'AFG' },
  { value: 'Arábia Saudita', label: 'Arábia Saudita', regiao: 'SAU' },
  { value: 'Armênia', label: 'Armênia', regiao: 'ARM' },
  { value: 'Azerbaijão', label: 'Azerbaijão', regiao: 'AZE' },
  { value: 'Bahrein', label: 'Bahrein', regiao: 'BHR' },
  { value: 'Bangladesh', label: 'Bangladesh', regiao: 'BGD' },
  { value: 'Brunei', label: 'Brunei', regiao: 'BRN' },
  { value: 'Butão', label: 'Butão', regiao: 'BTN' },
  { value: 'Camboja', label: 'Camboja', regiao: 'KHM' },
  { value: 'Cazaquistão', label: 'Cazaquistão', regiao: 'KAZ' },
  { value: 'China', label: 'China', regiao: 'CHN' },
  { value: 'Coreia do Norte', label: 'Coreia do Norte', regiao: 'PRK' },
  { value: 'Coreia do Sul', label: 'Coreia do Sul', regiao: 'KOR' },
  {
    value: 'Emirados Árabes Unidos',
    label: 'Emirados Árabes Unidos',
    regiao: 'ARE',
  },
  { value: 'Filipinas', label: 'Filipinas', regiao: 'PHL' },
  { value: 'Geórgia', label: 'Geórgia', regiao: 'GEO' },
  { value: 'Índia', label: 'Índia', regiao: 'IND' },
  { value: 'Indonésia', label: 'Indonésia', regiao: 'IDN' },
  { value: 'Irã', label: 'Irã', regiao: 'IRN' },
  { value: 'Iraque', label: 'Iraque', regiao: 'IRQ' },
  { value: 'Israel', label: 'Israel', regiao: 'ISR' },
  { value: 'Japão', label: 'Japão', regiao: 'JPN' },
  { value: 'Jordânia', label: 'Jordânia', regiao: 'JOR' },
  { value: 'Kuwait', label: 'Kuwait', regiao: 'KWT' },
  { value: 'Laos', label: 'Laos', regiao: 'LAO' },
  { value: 'Líbano', label: 'Líbano', regiao: 'LBN' },
  { value: 'Malásia', label: 'Malásia', regiao: 'MYS' },
  { value: 'Maldivas', label: 'Maldivas', regiao: 'MDV' },
  { value: 'Mianmar', label: 'Mianmar', regiao: 'MMR' },
  { value: 'Mongólia', label: 'Mongólia', regiao: 'MNG' },
  { value: 'Nepal', label: 'Nepal', regiao: 'NPL' },
  { value: 'Omã', label: 'Omã', regiao: 'OMN' },
  { value: 'Paquistão', label: 'Paquistão', regiao: 'PAK' },
  { value: 'Qatar', label: 'Qatar', regiao: 'QAT' },
  { value: 'Quirguistão', label: 'Quirguistão', regiao: 'KGZ' },
  { value: 'Rússia', label: 'Rússia', regiao: 'RUS' },
  { value: 'Singapura', label: 'Singapura', regiao: 'SGP' },
  { value: 'Síria', label: 'Síria', regiao: 'SYR' },
  { value: 'Sri Lanka', label: 'Sri Lanka', regiao: 'LKA' },
  { value: 'Tadjiquistão', label: 'Tadjiquistão', regiao: 'TJK' },
  { value: 'Tailândia', label: 'Tailândia', regiao: 'THA' },
  { value: 'Taiwan', label: 'Taiwan', regiao: 'TWN' },
  { value: 'Timor-Leste', label: 'Timor-Leste', regiao: 'TLS' },
  { value: 'Turcomenistão', label: 'Turcomenistão', regiao: 'TKM' },
  { value: 'Turquia', label: 'Turquia', regiao: 'TUR' },
  { value: 'Uzbequistão', label: 'Uzbequistão', regiao: 'UZB' },
  { value: 'Vietnã', label: 'Vietnã', regiao: 'VNM' },
  { value: 'Iêmen', label: 'Iêmen', regiao: 'YEM' },

  // África
  { value: 'África do Sul', label: 'África do Sul', regiao: 'ZAF' },
  { value: 'Angola', label: 'Angola', regiao: 'AGO' },
  { value: 'Argélia', label: 'Argélia', regiao: 'DZA' },
  { value: 'Benim', label: 'Benim', regiao: 'BEN' },
  { value: 'Botsuana', label: 'Botsuana', regiao: 'BWA' },
  { value: 'Burquina Faso', label: 'Burquina Faso', regiao: 'BFA' },
  { value: 'Burundi', label: 'Burundi', regiao: 'BDI' },
  { value: 'Cabo Verde', label: 'Cabo Verde', regiao: 'CPV' },
  { value: 'Camarões', label: 'Camarões', regiao: 'CMR' },
  { value: 'Chade', label: 'Chade', regiao: 'TCD' },
  { value: 'Comores', label: 'Comores', regiao: 'COM' },
  { value: 'Congo', label: 'Congo', regiao: 'COG' },
  { value: 'Costa do Marfim', label: 'Costa do Marfim', regiao: 'CIV' },
  { value: 'Djibuti', label: 'Djibuti', regiao: 'DJI' },
  { value: 'Egito', label: 'Egito', regiao: 'EGY' },
  { value: 'Eritreia', label: 'Eritreia', regiao: 'ERI' },
  { value: 'Essuatíni', label: 'Essuatíni', regiao: 'SWZ' },
  { value: 'Etiópia', label: 'Etiópia', regiao: 'ETH' },
  { value: 'Gabão', label: 'Gabão', regiao: 'GAB' },
  { value: 'Gâmbia', label: 'Gâmbia', regiao: 'GMB' },
  { value: 'Gana', label: 'Gana', regiao: 'GHA' },
  { value: 'Guiné', label: 'Guiné', regiao: 'GIN' },
  { value: 'Guiné-Bissau', label: 'Guiné-Bissau', regiao: 'GNB' },
  { value: 'Guiné Equatorial', label: 'Guiné Equatorial', regiao: 'GNQ' },
  { value: 'Lesoto', label: 'Lesoto', regiao: 'LSO' },
  { value: 'Libéria', label: 'Libéria', regiao: 'LBR' },
  { value: 'Líbia', label: 'Líbia', regiao: 'LBY' },
  { value: 'Madagascar', label: 'Madagascar', regiao: 'MDG' },
  { value: 'Malawi', label: 'Malawi', regiao: 'MWI' },
  { value: 'Mali', label: 'Mali', regiao: 'MLI' },
  { value: 'Marrocos', label: 'Marrocos', regiao: 'MAR' },
  { value: 'Maurícia', label: 'Maurícia', regiao: 'MUS' },
  { value: 'Mauritânia', label: 'Mauritânia', regiao: 'MRT' },
  { value: 'Moçambique', label: 'Moçambique', regiao: 'MOZ' },
  { value: 'Namíbia', label: 'Namíbia', regiao: 'NAM' },
  { value: 'Níger', label: 'Níger', regiao: 'NER' },
  { value: 'Nigéria', label: 'Nigéria', regiao: 'NGA' },
  { value: 'Quênia', label: 'Quênia', regiao: 'KEN' },
  {
    value: 'República Centro-Africana',
    label: 'República Centro-Africana',
    regiao: 'CAF',
  },
  {
    value: 'República Democrática do Congo',
    label: 'República Democrática do Congo',
    regiao: 'COD',
  },
  { value: 'Ruanda', label: 'Ruanda', regiao: 'RWA' },
  { value: 'Saara Ocidental', label: 'Saara Ocidental', regiao: 'ESH' },
  { value: 'São Tomé e Príncipe', label: 'São Tomé e Príncipe', regiao: 'STP' },
  { value: 'Seicheles', label: 'Seicheles', regiao: 'SYC' },
  { value: 'Senegal', label: 'Senegal', regiao: 'SEN' },
  { value: 'Serra Leoa', label: 'Serra Leoa', regiao: 'SLE' },
  { value: 'Somália', label: 'Somália', regiao: 'SOM' },
  { value: 'Sudão', label: 'Sudão', regiao: 'SDN' },
  { value: 'Sudão do Sul', label: 'Sudão do Sul', regiao: 'SSD' },
  { value: 'Tanzânia', label: 'Tanzânia', regiao: 'TZA' },
  { value: 'Togo', label: 'Togo', regiao: 'TGO' },
  { value: 'Tunísia', label: 'Tunísia', regiao: 'TUN' },
  { value: 'Uganda', label: 'Uganda', regiao: 'UGA' },
  { value: 'Zâmbia', label: 'Zâmbia', regiao: 'ZMB' },
  { value: 'Zimbábue', label: 'Zimbábue', regiao: 'ZWE' },

  // Oceania
  { value: 'Austrália', label: 'Austrália', regiao: 'AUS' },
  { value: 'Fiji', label: 'Fiji', regiao: 'FJI' },
  { value: 'Ilhas Marshall', label: 'Ilhas Marshall', regiao: 'MHL' },
  { value: 'Ilhas Salomão', label: 'Ilhas Salomão', regiao: 'SLB' },
  { value: 'Kiribati', label: 'Kiribati', regiao: 'KIR' },
  { value: 'Micronésia', label: 'Micronésia', regiao: 'FSM' },
  { value: 'Nauru', label: 'Nauru', regiao: 'NRU' },
  { value: 'Nova Zelândia', label: 'Nova Zelândia', regiao: 'NZL' },
  { value: 'Palau', label: 'Palau', regiao: 'PLW' },
  { value: 'Papua-Nova Guiné', label: 'Papua-Nova Guiné', regiao: 'PNG' },
  { value: 'Samoa', label: 'Samoa', regiao: 'WSM' },
  { value: 'Tonga', label: 'Tonga', regiao: 'TON' },
  { value: 'Tuvalu', label: 'Tuvalu', regiao: 'TUV' },
  { value: 'Vanuatu', label: 'Vanuatu', regiao: 'VUT' },
];

export default ListaPaises;
